package = [
    { name = "load-gaitrite", url = "https://github.com/RTO-Spinal-Stim/load-gaitrite.git" },
    { name = "load_xsens", url = "https://github.com/RTO-Spinal-Stim/load-xsens.git" },
    { name = "test-package", url = "https://github.com/mtillman14/test-repo.git" },
]
